zzxming/quill-table-up

src/modules/index.ts, src/modules/table-resize-common.ts, src/modules/table-resize-line.ts, src/modules/table-resize.ts
fix: when cell width already smaller than min width not allow drag
=> refactor: extract table resize drag handle function

eslint.config.js, src/modules/table-menu/table-menu-common.ts, src/modules/table-menu/table-menu-contextmenu.ts, src/modules/table-scrollbar.ts, src/style/color-picker.less, src/style/index.less, src/utils/color.ts, src/utils/components/color-picker.ts, src/utils/components/index.ts, src/utils/components/tooltip.ts, src/utils/utils.ts
=> feat: custom color picker

src/__tests__/unit/table-clipboard.test.ts, src/index.ts
=> fix: paste text copy from table doesn't work

src/__tests__/unit/table-clipboard.test.ts, src/__tests__/unit/utils.ts, src/formats/table-cell-format.ts, src/formats/table-cell-inner-format.ts, src/modules/table-paste-parser.ts
=> fix: error when cell attribute convert

README.md, docs/index.html, docs/index.js, docs/update-constants.js, docs/update-formats-value.js, src/__tests__/e2e/table-selection.test.ts, src/__tests__/unit/table-insert.test.ts, src/formats/table-cell-inner-format.ts, src/index.ts, src/modules/table-selection.ts, src/table-up.ts, src/utils/constants.ts, src/utils/types.ts
=> fix: cell should not editable when quill disabled

docs/index.html, docs/index.js, src/__tests__/unit/table-insert.test.ts, src/__tests__/unit/utils.ts, src/formats/table-cell-inner-format.ts, src/table-up.ts
=> fix: editor editable hack initial

src/__tests__/e2e/editor-page.ts, src/__tests__/e2e/table-selection.test.ts, src/__tests__/e2e/types.d.ts, src/__tests__/e2e/utils.ts, src/formats/table-row-format.ts, src/table-up.ts
=> feat: table cell selection keyboard handle

src/__tests__/e2e/table-selection.test.ts, src/modules/table-selection.ts
=> fix: selection update when text change

src/__tests__/e2e/table-menu.test.ts, src/__tests__/e2e/table-selection.test.ts, src/modules/table-menu/table-menu-common.ts, src/modules/table-menu/table-menu-contextmenu.ts, src/modules/table-menu/table-menu-select.ts, src/modules/table-resize/table-resize-box.ts, src/modules/table-selection.ts, src/utils/types.ts
=> fix: selection hide during color picker

src/__tests__/e2e/table-scrollbar.test.ts, src/modules/table-scrollbar.ts
=> fix: document select reset

src/formats/overrides/scroll.ts, src/table-up.ts
=> fix: quill enable default args

src/__tests__/unit/table-clipboard.test.ts, src/__tests__/unit/table-insert.test.ts, src/__tests__/unit/utils.ts, src/modules/index.ts, src/modules/table-clipboard.ts, src/table-up.ts
=> fix: move html matcher handler to clipboard

src/__tests__/e2e/table-selection.test.ts, src/formats/overrides/block.ts, src/modules/table-selection.ts
=> fix: toolbar clean format error

src/__tests__/e2e/table-menu.test.ts, src/__tests__/e2e/table-selection.test.ts, src/modules/table-menu/table-menu-common.ts
=> feat: color picker trigger by click

src/__tests__/e2e/table-hack.test.ts, src/__tests__/unit/table-hack.test.ts, src/table-up.ts
=> fix: format trigger wrong source

src/__tests__/unit/table-hack.test.ts, src/__tests__/unit/table-redo-undo.test.ts, src/formats/overrides/block.ts, src/table-up.ts, src/utils/is.ts
=> feat: clean button clean cell style

src/__tests__/e2e/editor-page.ts, src/__tests__/e2e/table-selection.test.ts, src/modules/table-selection.ts
=> feat: keyboard handle delete table

src/modules/table-menu/table-menu-select.ts, src/style/table-resize-scale.less
=> fix: resize scale cursor and add offset with select menu

src/modules/table-menu/constants.ts, src/modules/table-menu/index.ts, src/modules/table-menu/table-menu-common.ts
=> feat: export table menu tools

src/__tests__/unit/table-hack.test.ts, src/__tests__/unit/table-redo-undo.test.ts, src/table-up.ts, src/utils/transformer.ts
=> fix: border style clean

src/__tests__/e2e/table-blots.test.ts, src/formats/table-col-format.ts, src/formats/table-colgroup-format.ts, src/formats/table-main-format.ts
=> fix: table full width switch status error

docs/test.html, docs/test.js, src/__tests__/e2e/table-scrollbar.test.ts, src/__tests__/e2e/table-selection.test.ts, src/modules/table-scrollbar.ts, src/table-up.ts
=> fix: table toolbox should not have offset when container have padding

src/__tests__/unit/table-clipboard.test.ts, src/modules/table-clipboard.ts
=> fix: cell convert

src/__tests__/unit/table-clipboard.test.ts, src/modules/table-clipboard.ts
=> fix: rowspan and col span attribute convert

src/__tests__/unit/table-redo-undo.test.ts, src/formats/container-format.ts, src/formats/table-cell-inner-format.ts, src/formats/table-col-format.ts
=> fix: undo and redo remove last column

src/__tests__/e2e/table-selection.test.ts, src/__tests__/unit/table-hack.test.ts, src/table-up.ts
=> fix!: format hack use selectedTd when range not in cell

src/__tests__/unit/table-blots.test.ts, src/formats/table-wrapper-format.ts
=> fix: table around line should allow `list` and `code-block`

src/__tests__/unit/table-clipboard.test.ts, src/modules/table-clipboard.ts
=> feat: convert style on table

src/__tests__/e2e/table-clipboard.test.ts, src/formats/table-cell-format.ts, src/modules/table-clipboard.ts, src/utils/index.ts, src/utils/style-helper.ts, src/utils/transformer.ts
=> fix: get css with style property

src/__tests__/unit/table-redo-undo.test.ts, src/formats/overrides/block-embed.ts, src/formats/overrides/block.ts, src/formats/table-cell-inner-format.ts, src/formats/utils.ts
=> fix: format Block and BlockEmbed with TableCellInner get wrong delta

src/__tests__/e2e/table-keyboard-handler.test.ts, src/__tests__/unit/table-insert.test.ts, src/__tests__/unit/table-redo-undo.test.ts, src/formats/overrides/block-embed.ts, src/formats/overrides/block.ts, src/formats/table-cell-inner-format.ts
=> fix: BlockEmbed in table extra \n effect history stack reset

src/modules/table-resize/table-resize-box.ts
=> fix: issue https://github.com/zzxming/quill-table-up/issues/245
